version: 0.2

phases:
  pre_test:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull 
  test:
    commands:
      - echo Run performance test
      - docker run -i loadimpact/k6 run - <scripts/test.js
  post_test:
    commands:
      - echo Performance test complete
